### ISSUE TITLE
Definition of EXTRA

### ISSUE THREAD

**Issue by labra** [shexSpec/shex#10]
The `EXTRA` qualifier allows one to say that some property can contain extra values apart from the values defined in the shape. 

For example, if we have:

```
<S> { <p> [1 2 3] }
```

We are saying that nodes with shape `S` can have only one value for property `<p>` that must belong to the set `[1 2 3]`. So, for example:

```
# Given <S> { <p> [1 2 3] }
<x> <p> 1 .  # Satisfies <S> 
<y> <p> "hi" . # Doesn't satisfy <S> 
``` 

If we add `EXTRA <p>` then we are allowing extra values for property `<p>`, i. e.:

```
# Given <S> EXTRA <p> { <p> [1 2 3] }
<x> <p> 1 .  # Satisfies <S> 
<y> <p> "hi" . # Doesn't satisfy <S> 
``` 

The spec doesn't clarify what happens if the values of `<p>` overlap with the values defined inside the shape. There are two possibilities:

1.- Restricted EXTRA 
2.- Unrestricted EXTRA

## 1.- Restricted EXTRA
The values of properties in the scope of EXTRA are restricted to be different from the values declared for that property inside the Shape

```
<S> EXTRA <p> { <p> X } == <S> {<p> X; <p> NOT X* }
````
In the previous example:

```
# If we have <S> EXTRA <p> { <p> [1 2 3] } == <S> {<p> [1 2 3]; <p> NOT [1 2 3]* }
<x> <p> 1, "hi" . # Satisfies <S> 
<x> <p> 1, 2 . # Doesn't satisfy <S> because there must be only one <p> with values in [1 2 3]
```
One problem of this possibility is that the implementation may be more complex as it must take into account all the appearances of `<p>` in a shape. For example, if we have two appearances of `<p>` it should be:

```
<S> EXTRA <p> { <p> X; <p> Y  } == <S> { <p> X; <p> Y; <p> NOT X AND NOT Y
```

## 2.- Unrestricted EXTRA

Another possibility is to the define EXTRA as:

```
<S> EXTRA <p> { <p> X } == <S> { <p> X; <p> .* }
```

In the previous example:

```
# If we have <S> EXTRA <p> { <p> [1 2 3] } == <S> {<p> [1 2 3]; <p> .* }
<x> <p> 1, "hi" . # Satisfies <S> 
<y> <p> 1, 2 .  # Satisfies <S> 
```

The result may look less correct. For example, the `<y>` in previous example has two values for `<p>` inside `[1 2 3]` while the shape declaration suggest that it must have only one.

This possitive is easier to implement.

**Comment by labra** [comment]
My first implementation used _unrestricted EXTRA_, however, I changed later to try to define _restricted EXTRA_ in ShExcala and I am not sure I covered all the cases.

In my opinion, both interpretations are possible and maybe, we should use the _unrestricted EXTRA_ because it is less complex and more intuitive.

**Comment by ericprud** [comment]
The problem with unrestricted EXTRA is that it leaves no meaning to max cardinality:
  <S> EXTRA :p1 { :p1 IRI {1,2} }
With restricted EXTRA, that would fail the data:
  <s> :p1 <o1>, <o2>, <o3> .
I vote we keep restricted EXTRA.

**Comment by labra** [comment]
I agree with that. The main concern would be the _extra_ complexity that will be required to negate all the appearances of the predicate. For example, given:

```
<S> EXTRA <p> { <p> IRI; (<p> @<T> |  <p> @<U>) } 
```

should be the same as:

```
<S> { <p> IRI; (<p> @<T> |  <p> @<U>); <p> NOT (IRI OR @<T> OR @<U>) } 
```

Anyway, I also vote to keep the _restricted_ EXTRA semantics.
