### ISSUE TITLE
Make keyword 'a' case insensitive.

### ISSUE THREAD

**Issue by thewilly** [shexSpec/shex#101]
Hi, I'm currently implementing [shex-lite](https://github.com/weso/shex-lite) (early-early version yet), which is an small subset of ShEx. I know that the keyword 'a' comes from m3 and later from turtle, but maybe, as the language shex is completly case insensible you might consider to make the 'a' keyword case insensitive too. It will simplify the Antlr grammar by just declaring case insentivity at parsing time, instead of defining a fragment for every character in upper and lower case.

By the way any hint to define [shex-lite](https://github.com/weso/shex-lite) subset will be helpful.

Thanks.

**Comment by ericprud** [comment]
Oof, you're making me wrestle with a sunk-cost fallacy.

I think we should be compatible with how Turtle and SPARQL "ought to be", so if we decide to make it case-insensitive, we're signalling that it ought to be case-insensitive in the rest of the stack.

**Comment by alejgh** [comment]
Thank you for the response @ericprud. We imagined that it would not be correct going against Turtle and SPARQL case-insensitivity rules, but we still wanted to receive your input on the subject.

We'll keep the 'a' keyword case-sensitive in shex-lite too 😊. This issue can be closed.
