### ISSUE TITLE
Should a shape imply NONLITERAL?

### ISSUE THREAD

**Issue by ericprud** [shexSpec/shex#13]
Currently,
```
PREFIX : <http://a.example/>
<s> :p1 1 .
```
trivially satisfies
```
PREFIX : <http://a.example/>
<S1> { :p1 @<S2> }
<S2> { :p2 .? }
```
because :p2 is optional.
As a workaround, I added a NONLITERAL constraint::
```
PREFIX : <http://a.example/>
<S1> { :p1 @<S2> }
<S2> NONLITERAL { :p2 .? }
```
Should that be implicit when there's a shape (as implied by {}s)? RDF currently (and maybe forever) prohibits literals as subjects, which kind of works to our favor in this case.

This issue exists for nested shapes as well, e.g.
```
PREFIX : <http://a.example/>
<S1> { :p1 { :p2 .? } }
```
vs.
```
PREFIX : <http://a.example/>
<S1> { :p1 NONLITERAL { :p2 .? } }
```

**Comment by gkellogg** [comment]
Yes, I think there is both a structural and a semantic part to this:

    <S1> LITERAL {:p1 @<S2>}

Should probably be a structural error, for which we can create a negativeStructure test.

If we have `<S2> {:p1 @<S3>}`, the triple expression should never match given a literal object.

**Comment by labra** [comment]
👍

**Comment by ericprud** [comment]
I think there's an infinite number of possible structural errors.
  <noncode> IRI AND LITERAL
  <nonshape> CLOSED {} AND { <p> . }
I was simply proposing that totally independent of any surrounding ShapeAnd, a validating a Shape would entail checking that if it has outgoing arcs, it's not a literal. I'm a little concerned about the heuristic nature. Dimitris is going to say that he thinks it should be a ShExLint feature instead of an aspect in the spec, aren't you @jimkont?

**Comment by jimkont** [comment]
Yes, this was my proposal, to make this a lint feature and mark this as a warning.

If the user wanted to define it this way on intention, would there be a way to do it with the implicit `nonliteral`?
i.e. this value should have no outgoing arcs (iri or literal) but if it has arcs it should be `{ :p2 .? }`

**Comment by ericprud** [comment]
I : -1:'d my original proposal and +1:'d dimitris's (@jimkont) proposal above to leave it to a lint feature.

**Comment by ericprud** [comment]
PROPOSAL: close
REASON: leave to best practice or lint tool
PARTICIPANTS: @labra, @ericprud, @gkellogg, @jimkont

**Comment by jimkont** [comment]
RESOLVED in 2017-02-17 meeting accepting https://github.com/shexSpec/shex/issues/13#issuecomment-280250179 and adding a note with an example on the spec

ericP: +1
Harold: +1
Tom: +1
Andra: +1
LarsG: +1
Dimitris: +1
