### ISSUE TITLE
Should literals have stems?

### ISSUE THREAD

**Issue by ericprud** [shexSpec/shex#14]
Stems are a syntactic shortcut for regular expressions constraints. They represent a large savings over the analogous complex `and`, `or` and `not` expressions. It would frequently be nice to offer the same expressivity for literals, e.g. in FHIR/RDF where uris are represented as literals.

**Comment by gkellogg** [comment]
This would require almost no change in my implementation.

**Comment by labra** [comment]
I also agree that they can be a useful feature to add...+1 to add them.

**Comment by ericprud** [comment]
added in 2.0
