### ISSUE TITLE
Remove "negated properties" from features in Shex.io Webpage and in primer

### ISSUE THREAD

**Issue by labra** [shexSpec/shex#15]
Negated properties should be removed from features in http://shex.io web page

**Comment by ericprud** [comment]
you can still get negation, but it's of the form

    <S> {
      foaf:name .;
      foaf:givenName .{0,0};
      foaf:familyName .{0,0}
    }

Does that count as negation?

**Comment by labra** [comment]
But in that case, we should define `!` as an alias for `{0,0}` and I am not sure if that was the case. 

I remember that negated properties had some semantic implications that motivated us to remove them from ShEx 2.0 (see issue #11 for some cases).

I raised this issue just as a reminder to remove them from the primer the web page until they are part of the language.

**Comment by ericprud** [comment]
I've updated the [primer negation example](https://shexspec.github.io/primer/#negated-properties) and added a [spec negation example](https://shexspec.github.io/spec/#example-negation) explaining the use of the {0,0} negation idiom.

PROPOSAL: close
REASON: it is satisfied by the [primer](https://shexspec.github.io/primer/#negated-properties) and [spec](https://shexspec.github.io/spec/#example-negation)
PARTICIPANTS: @labra, @ericprud
