### ISSUE TITLE
Clarify if literal values are checked to belong to their declared datatypes

### ISSUE THREAD

**Issue by labra** [shexSpec/shex#19]
Given:

```
prefix : <http://example.org/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

:S { :p xsd:integer }
```

and 

```
prefix : <http://example.org/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

:x :p "Hi"^^xsd:integer .
```

Should ShEx precessors accept it as valid or fail? 

Another possibility is to leave that as implementation dependent, where some implementations could give some warning saying that although the RDF literal is declared as `xsd:integer`, its lexical form doesn't match the rules for integers. 

If we decide that it should fail, then we should define which rules and built-in datatypes ShEx support, I would suggest the XML Schema datatypes.

**Comment by gkellogg** [comment]
Note that we handled this in CSVW for a subset of XSD terms that seemed to make sense in the RDF context (see [Datatypes](https://www.w3.org/TR/tabular-metadata/#datatypes)). When validating, processors **must** verify that the value is consistent with the requirements of the datatype. The behavior is undefined for other datatypes (which allows a given processor to extend validation). As described for `base`:

> All values of the datatype **must** be valid values of the base datatype.

Derived datatypes also allow other restrictions, quite similar to what we have for `NodeConstraint`.

IMO, it makes sense to validate object values where the datatype is specified, at least for the set of datatypes defined for CSVW based on `anyAtomicType`. I believe we skipped `NOTATION`, `NCName` (and derivatives) in addition to `anyType`, and _all complex types_. If needed, I can probably dig up the discussion as to why these datatypes were excluded.

**Comment by ericprud** [comment]
👍

I'd be happy to go either way on this but I note that in a meeting of the data-shapes WG, there was a general call for validating the lexical forms of datatypes. IIRC, TQ resisted and it didn't go into the spec but I think the expectation exists so +1 to testing lexical validity on nodes tested against a datatype.

**Comment by labra** [comment]
Once we resolve this issue, we should update the spec before closing it. The current spec contains at the end of section 4.4.3 the following paragraph:

> The RDF Data Shapes Working Group decided that validation should test the lexical form of literals when testing the datatype (resolution). Should ShEx do that? 

I propose to change it to a note saying that it has been resolved.

**Comment by ericprud** [comment]
I've updated [the spec](https://shexspec.github.io/spec/#datatype) and the [test suite](https://github.com/shexSpec/shexTest/commit/8846ed3dba26d79b949102511ea2b4619a9296a8) with ~120 new tests.

PROPOSAL: close
REASON: implemented
PARTICIPANTS: @labra, @ericprud, @gkellogg

**Comment by gkellogg** [comment]
Done.
