### ISSUE TITLE
Design a nice logo for ShEx

### ISSUE THREAD

**Issue by labra** [shexSpec/shex#26]
We could use the logo for the webpage, the community group, the shexSpec organization, etc.

Proposals?

**Comment by ericprud** [comment]
I've been using a [variant of the RDF logo](https://www.w3.org/2015/ShEx-Icon.svg) which may inspire others to do better.

**Comment by ericprud** [comment]
Here are some more variants:![some more variants](https://files.gitter.im/shapeExpressions/Lobby/F432/ShEx-Icons.png)

**Comment by hsolbrig** [comment]
Propose row 3 column 3 and bones

**Comment by jessevdam** [comment]
+1 row 3 column 3

**Comment by tombaker** [comment]
+1

**Comment by jimkont** [comment]
Based on thumbs-up votes by @ericprud , @hsolbrig , @andrawaag , @gkellogg , @jimkont, @emulatingkat, @jessevdam  and @tombaker 

ShEx has now the shex-orange-yellow.svg as the official logo!
