### ISSUE TITLE
Support for flags in regex pattern

### ISSUE THREAD

**Issue by labra** [shexSpec/shex#28]
The `pattern` facet in the current spec doesn't have support for the flags optional parameter. 

The issue has already been detected as appears in the specification so adding this issue here is just to unify the issues in a single place.

How could we represent flags in the compact syntax?

**Comment by ericprud** [comment]
PROPOSAL: adopt ~/regexp/ syntax for regular expressions
REASON: better than having no flags
DIFFS: [shexTest](https://github.com/shexSpec/shexTest/compare/master...regex), [shex.js](https://github.com/shexSpec/shex.js/compare/master...regex)

**Comment by labra** [comment]
I voted +1 but I think the ShExC BNF grammar (and the ANTLR) still need to be updated to reflect the change. 

Currently, we have production 34. 

```
[34]  stringFacet 	   ::=    	   stringLength INTEGER
                                   | "PATTERN" string
                                   | "~" string
```

and I suppose it should be something like:

```
[34]  stringFacet 	   ::=    	   stringLength INTEGER
                                   | "~" "/" pattern "/" flags
```

where `pattern` and `flags` should also be defined.

**Comment by ericprud** [comment]
yep, i did this in my impl:
```diff
 [25]    stringFacet ::= stringLength INTEGER
                       | REGEXP
-                      | "PATTERN" string
-                      | '~' string  # shortcut for "PATTERN"
+[63]    REGEXP      ::= '/' ([^#x2f#x5C#xA#xD] | '\\' [tbnrf\\/] | UCHAR)* '/' [smix]*
```
which allows for repetition of flags but is pretty good otherwise.
The edits are pretty small for spec/index.html and grammar/* so I didn't bother to create branches for them.

**Comment by ericprud** [comment]
merged with changes to [/spec](https://github.com/shexSpec/spec/commit/69665bd5924ce1536c18a4242df571101afa347f) and [/grammar](https://github.com/shexSpec/grammar/commit/0a83e1cf981f485a2bcf6650f5cea419bffecdd1)
