### ISSUE TITLE
Title of document "Shape Expression Vocabulary Terms"

### ISSUE THREAD

**Issue by tombaker** [shexSpec/shex#33]
[Shape Expression Vocabulary Terms](http://shexspec.github.io/ns/) could more simply be called "Shape Expression Vocabulary", following the pattern of [Web Annotation Vocabulary](https://www.w3.org/TR/annotation-vocab), [Data Catalog Vocabulary](https://www.w3.org/TR/vocab-dcat/), etc.

**Comment by jimkont** [comment]
This was an editorial issue and the suggestion by @tombaker is already adopted in https://github.com/shexSpec/shexspec.github.io/commit/b63802f1dcc2125dca53973a494af315cbb4985c
