### ISSUE TITLE
ShapeMap definition in the spec

### ISSUE THREAD

**Issue by labra** [shexSpec/shex#36]
This issue is aimed to discuss [the following comment](https://shexspec.github.io/spec/#shape-map) in the spec:

> Since a node may have multiple shapes, this should either be a mapping from a node to a set of shapes { "n1": [ "S1", "S2"], "n2": [] } or a list of node-shape pairs [ ["n1", "S1"], ["n1", "S2"] }. Which is easier to understand? 

I have no strong opinion on this. I think I prefer the first option (a map from a node to a set of shapes)

**Comment by ericprud** [comment]
I've implemented the first option:

> A ShapeMap is a mapping from node to a set of shapes (Node1: [Shape2, Shape3, …]) where...

PROPOSAL: close
REASON: 
PARTICIPANTS: @labra, @ericprud, @gkellogg (out of band)
