### ISSUE TITLE
Update Antlr grammar to be in synch with the recent changes in BNF

### ISSUE THREAD

**Issue by labra** [shexSpec/shex#39]
This issue is just a reminder that we need to update the [antlr grammar](https://github.com/shexSpec/grammar/blob/master/ShExDoc.g4) to be in synch with the changes proposed to solve #38.

**Comment by ericprud** [comment]
I'm not completely confident, but I think I've managed to keep this up to date with the yacker and the BNF. It would be cool to resolve this by writing a fairly trivial ShExC-to-ShExJ tool in some language with good ANTLR bindings.

**Comment by ericprud** [comment]
Closed based on Harold's implementation of shexc_to_shexj.
