### ISSUE TITLE
^^-style facet arguments

### ISSUE THREAD

**Issue by ericprud** [shexSpec/shex#41]
The ShEx2 grammar currently allows [both numeric literals (`5, 5.0, 5E0`) and `^^`-style arguments](https://shexspec.github.io/spec/#prod-numericFacet). ShExR.shex accepts [xsd:integer OR xsd:decimal OR xsd:double](https://github.com/shexSpec/shexTest/blob/master/doc/ShExR.shex#L81) for those arguments. (I noticed this because I had to add `OR xsd:float` for the three {Min,Max}{in,ex}clusive-float.ttl files.)

We have tests for `^^xsd:float` but would have to define what datatypes were permitted, decide what to do with schemas with different datatypes, and add comprehensive tests. Alternatively, we can eliminate the `^^`-style arguments without reducing expressivity (c.f. [1floatMininclusiveINTEGER_pass-equalLead](https://github.com/shexSpec/shexTest/blob/master/validation/manifest.ttl#L5499)) because of [numeric type promotion](https://shexspec.github.io/spec/#xs-numeric).

PROPOSE: remove ` | string "^^" datatype` from [numericFacet](https://shexspec.github.io/spec/#prod-numericFacet), the three schemas [1floatMaxinclusivexsd-float](https://github.com/shexSpec/shexTest/blob/master/schemas/1floatMaxinclusivexsd-float.json), [1floatMinexclusivexsd-float](https://github.com/shexSpec/shexTest/blob/master/schemas/1floatMinexclusivexsd-float.json), [1floatMininclusivexsd-float](https://github.com/shexSpec/shexTest/blob/master/schemas/1floatMininclusivexsd-float.json), and the [related validation tests](https://github.com/shexSpec/shexTest/blob/master/validation/manifest.ttl#L8074).
REASON: complex and does not add expressivity
PARTICIPANTS: @ericprud, @gkellogg, @labra
DIFFS: see `facet-typed-literal` branches in [spec](https://github.com/shexSpec/spec/compare/gh-pages...facet-typed-literal), [grammar](https://github.com/shexSpec/grammar/compare/master...facet-typed-literal), [shexTest](https://github.com/shexSpec/shexTest/compare/master...facet-typed-literal), [shex.js](https://github.com/shexSpec/shex.js/compare/master...facet-typed-literal)
- [7 schemas removed](https://github.com/shexSpec/shexTest/compare/master...facet-typed-literal#diff-812a46ae982a29ebdee2f86dbe52dd46)
- [13 validation tests removed](https://github.com/shexSpec/shexTest/compare/master...facet-typed-literal#diff-e45ec9fb9aead8fb5d8f45ef1915cd9e)

**Comment by gkellogg** [comment]
`^^` literals useful for date, dateTime, and time, also boolean. May also be useful for restrictions on numbers and dates. Right now, dates/times/boolean fall into the `numericFacet`, but perhaps we need something else?

**Comment by gkellogg** [comment]
These come into play for datatype validation, not necessarily facets, so I'm good.

**Comment by ericprud** [comment]
merged
