### ISSUE TITLE
Regular Expression BNF wrong

### ISSUE THREAD

**Issue by gkellogg** [shexSpec/shex#45]
The new `stringFacet` rule is:

```
[34]   	stringFacet	   ::=   	   stringLength INTEGER
                                          | "PATTERN" string
                                          | "~" string
```

However, `string` uses one of the `STRING_LITERAL` terminals, which is quoted. Instead, I suggest adding a new terminal:

    [XX]    PATTERN               ::= "/" ([^#x2f#x5C#xA#xD] | '\\' [tbnrf\\/] | UCHAR)+ "/" [smixq]*

and using `"~" PATTERN`.

**Comment by ericprud** [comment]
updated -- now:
  [34] stringFacet ::= stringLength INTEGER | REGEXP
    https://shexspec.github.io/spec/#prod-stringFacet
  [63] <REGEXP> ::= '/' ([^/\\\n\r] | '\\' [nrt\\|.?*+(){}$-\[\]^/] | UCHAR)+ '/' [smix]*
    https://shexspec.github.io/spec/#term-REGEXP

PROPOSE: close
REASON: fixed
