### ISSUE TITLE
Generalize stems to support language tags

### ISSUE THREAD

**Issue by labra** [shexSpec/shex#46]
One part of issue #4 is to be able to declare that the objects associated with some predicate are string language tagged literals for some specific languages. 

For example, we may want to declare that the values of `rdfs:label` are language tagged literals in English, French or Spanish with a syntax like:

```
<S> { rdfs:label [@en @es @fr]
```

From a semantics point of view, this mechanism is similar to stems and we can solve it by generalizing the types of stems to include also language tagged stems.  

We could even have stems on language tags as: `@en~` to represent different variants of English. 

@eric has already started to implement this mechanism in a [branch](https://github.com/shexSpec/shex.js/tree/stem) and has developed some tests for it, so I would propose to include this feature in ShEx 2.0

**Comment by gkellogg** [comment]
This is in the 2.0 release now, as is support for Literal stems.
