### ISSUE TITLE
Release Premer

### ISSUE THREAD

**Issue by gkellogg** [shexSpec/shex#51]
Suggestion to release the current version of the Primer.

**Comment by emulatingkat** [comment]
In section 1 "Quick Start" there are two links to the RDF Primer, do we want both?

**Comment by emulatingkat** [comment]
In section 3.3 in the box for "Failing Data (Turtle) the word unsigned is misspelled.

**Comment by emulatingkat** [comment]
Unsigned also needs to be changed in the Validation Results table in 3.3.

**Comment by tombaker** [comment]
deleted extra reference to primer - see https://github.com/shexSpec/primer/commit/91587a16f55d651310a41d7475768ffced9229d8

**Comment by ericprud** [comment]
added comment around typo to indicate that it's deliberate:
  ex:unsinged ; # <-- typo

**Comment by emulatingkat** [comment]
As I was reading through the Primer I found the "Shape Expressions Definition" document helpful to support my understanding.

Currently I don't see a pointer to the Definition document in the Primer. Would it be helpful to point to the Definition document within the Primer?

**Comment by emulatingkat** [comment]
Monday check-in @gkellogg would you like to discuss anything before voting?

**Comment by tombaker** [comment]
See: https://github.com/shexSpec/primer/commit/f89a53e6f6572afc47f36bdceb955402afd11515
* removed citation to rdf11-concepts in Abstract, leaving clickable link to ../spec.
* added reference to [[shex-defn]] to the first sentence of Quick Start.  Sentence now reads:
```
This primer, a companion to the full ShEx language specification [[shex-defn]],
focuses on the common use case of validating instance data.
```
In ReSpec, I do not see where it is possible to add a Reference.  Could someone please help by adding a reference to http://shex.io/spec/ (aka https://shexspec.github.io/spec/)?

**Comment by tombaker** [comment]
Re: https://shexspec.github.io/spec/ - shouldn't it list its own URI in the header?  It links to the test suite, bug tracker, and Github repo, but not to itself.

**Comment by gkellogg** [comment]
@tombaker I'll take care of it.

**Comment by gkellogg** [comment]
Regarding losing a link to itself, this is largely a function of the specStatus link. Making it CG-FINAL would likely do this, but the question came up yesterday if this was really a final release, or more like a Candidate Release. We also need to determine permanent versions URIs.

**Comment by emulatingkat** [comment]
Do the decision about final release/candidate release and the determination of permanent version URIs need to be addressed before publication?

**Comment by gkellogg** [comment]
@ericprud and I discussed this yesterday. If this is a "Final Release", then yes, there should be versioned URIs, probably off of shex.io/spec, or something (http://json-ld.org does this, along with references to previous drafts). But, if this is more of a "Candidate Release", then we're effectively sending links to the editor's drafts. However, it would be useful to timestamp what's sent out, for future reference.

As an alternative, we could create /release directors in shexspec.github.io/spec and /primer, and put timestamped versions there and reference that for the release.

shex.io, and shexspec.github.io should have references to these things.

**Comment by gkellogg** [comment]
Published locations are now http://shex.io/shex-semantics and http://shex.io/shex-primer. These are both linked to the time-stamped versions. Also shex.io/spec and shex.io/primer will redirect. The shexspec.github.io links are kept for editors drafts.
