### ISSUE TITLE
Update CG page

### ISSUE THREAD

**Issue by tombaker** [shexSpec/shex#52]
I have spoken to at least one person who looked for the latest publication announcement on the [Shape Expressions Community Group web page](https://www.w3.org/community/shex/).

Perhaps we could just use the [announcement text](https://lists.w3.org/Archives/Public/semantic-web/2017Mar/0083.html) for a blog post?

**Comment by gkellogg** [comment]
Done: https://www.w3.org/community/shex/2017/03/28/shex-2-0-candidate-release/
