### ISSUE TITLE
Does data type or language make sense in stems?

### ISSUE THREAD

**Issue by hsolbrig** [shexSpec/shex#55]
IRI, Literal and Language stems are all intended to function as string comparisons -- the string representations of the respective types match when they _start with_ the stem.   Currently, the ```exclusions``` of ```IriStemRange``` and the ```stem``` and ```exclusions``` of ```LiteralStem```, ```LiteralStemRange```, ```LanguageStem``` and ```LanguageStemRange``` refrence ```objectValue```, which is defined as ```IRI|ObjectLiteral```

I would argue that ```language``` and ```type``` make no sense in the context of string comparisons. 

**Recommendation:**
objectValue      = IRI|ObjectLiteral ;
IriStem          { stem:IRI } # IriStemRange with exclusions
IriStemRange     { stem:(IRI|Wildcard) exclusions:[~~objectValue~~IRI | IriStem +]? }
LiteralStem      { stem:~~ObjectLiteral~~STRING } # LiteralStemRange with exclusions
LiteralStemRange { stem:(~~ObjectLiteral~~STRING|Wildcard) exclusions:[~~objectValue~~STRING|LiteralStem +]? }
LanguageStem     { stem:~~ObjectLiteral~~LANGTAG } # LanguageStemRange with exclusions
LanguageStemRange{ stem:(~~ObjectLiteral~~LANGTAG | Wildcard) exclusions:[~~objectValue~~LANGTAG | LanguageStem +]? } 

LANGTAG : ([a-zA-Z])+ ("-" ([a-zA-Z0-9])+)*

See: https://github.com/shexSpec/shexTest/compare/master...Stem-string for changes to test cases

**Comment by ericprud** [comment]
no

**Comment by gkellogg** [comment]
See https://github.com/shexSpec/shex/issues/54#issuecomment-292019551 for a discussion of why this breaks with JSON-LD in 1.0. I don't think we can do this until we move to JSON-LD 1.1.

**Comment by ericprud** [comment]
PROPOSED : that datatype stems don't make sense and language stems are covered by the merged Stem-string branche.

Interested: Harold, Gregg, ericP
