### ISSUE TITLE
language-value

### ISSUE THREAD

**Issue by ericprud** [shexSpec/shex#68]
ShExJ has no representation for `[@en @fr]` (lower left in table below). We have all combinations of {Iri,String,Language}Stem but the non-stem value set values are represented by their equivalent RDF terms, i.e. IRI and xsd:string. There was no way to represent something that would match any string with a particular language tag. (The grammar implied there was, but didn't define an associated abstract syntax type.) I added a `{ type: Language, value: "en" }` type to a [shex.js/language-value branch](https://github.com/shexSpec/shex.js/compare/language-value) [[try it](http://rawgit.com/shexSpec/shex.js/language-value/doc/shex-simple.html?interface=appinfo&schema=PREFIX%20my%3A%20%3Chttp%3A%2F%2Fmy.example%2F%3E%0A%0Amy%3AIssueShape%20%7B%0A%20%20my%3Astatus%20%5B%40en%5D%3B%0A%7D%0A&data=PREFIX%20my%3A%20%3Chttp%3A%2F%2Fmy.example%2F%3E%0A%0A%3CObs1%3E%0A%20%20my%3Astatus%20%20%20%20%22final%22%40en%20.%0A&shape-map=%3Chttp%3A%2F%2Fa.example%2FObs1%3E%40my%3AIssueShape)].

| X        | X (term)            | XStem                 | XStemRange                |
| ---:     | :---                | :---                  | :---                      |
| IRI      | `[<IRI1> ex:IRI2 ]` | `[<IRI1>~ ex:IRI2~ ]` | `[<IRI1>~ - ex:IRI123~ ]` |
| literal  | `["str1" "str2"]`   | `["str1"~ "str2"~]`   | `["str1"- "str12"~]`      |
| langauge | `[@en @fr]`         | `[@en~ @fr~]`         | `[@en~ - @en-fr~]`        |

We can add this at the last moment or document it as a bug and leave it until 2.1.

**Comment by gkellogg** [comment]
Also see https://github.com/shexSpec/shexspec.github.io/pull/8
