### ISSUE TITLE
language stem should respect langMatches semantics

### ISSUE THREAD

**Issue by VladimirAlexiev** [shexSpec/shex#71]
The following shape: 
`:SpanishProduct { schema:label [ @es~ ]  }`
Declares that products must have a label in Spanish or any variant of it (eg `es-ES` vs `es-AR`).

But LanguageStem is defined as simple prefix match (http://shex.io/shex-semantics/#nodeIn):
> s is a LanguageStem and n is a language-tagged string with a language tag l 
> and `fn:starts-with(l, st)` 

It has these defects:
- it will match language `"Carro"@ese` where `ese` is Ese Ejja, and I don't think those people got cars ;-)
- it won't match `"Carro"@ES` but lang tags are defined to be case-insensitive.
- (instead of `st` should refer to `s`)

Instead of simple prefix match, it should comply with https://www.w3.org/TR/sparql11-query/#func-langMatches semantics. RFC4647 defines tags for lang, script, dialect, region etc etc; and that it's case-insensitive. Assuming `s` doesn't end in `-` and assuming `.` represents concat, it can be defined eg like:
`regex (l, "(^".s."$)|(^".s."-)", "i")`
Note: a simpler regex would be `"^".s."($|-)"` but I don't believe the last part of it is valid.

Aside: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry is a bit unreadable. The script https://gist.github.com/VladimirAlexiev/8733439 turns it into this more readable [google sheet](https://docs.google.com/spreadsheets/u/1/d/1M1yv9aBUmc-NyCJX69vOLUmH2uIglSwmDwgRgByI1AI/edit)

TEST: @ericprud gave this example URL. For me, it doesn't load the test on first load (or control-shift-R) but loads it on second refresh (control-R):
http://rawgit.com/shexSpec/shex.js/master/doc/shex-simple.html?schema=%3CS%3E%20%7B%20%3Cp%3E%20%5B%40aa~%5D%20%7D&data=%3Cexact%3E%20%3Cp%3E%20%22exact%22%40aa%20.%0A%3Csub%3E%20%3Cp%3E%20%22sub%22%40aa-ES%20.%0A%3CshouldFail%3E%20%3Cp%3E%20%22shouldFail%22%40aaa-ES%20.%0A&shape-map=%7BFOCUS%20%3Cp%3E%20_%7D%40%3CS%3E

**Comment by jimkont** [comment]
Resolved with [20170915 meeting ](https://github.com/shexSpec/shex/blob/master/meetings/20170915-minutes.md)

**Resolution**: change language tag matching to follow RFC4647 per

voted by: Andra, Kat, ericP, tom

**Comment by ericprud** [comment]
See [~ LanguageStem follows rfc4647](https://github.com/shexSpec/spec/commit/c55643a67b00bd7f7ab0c0334343c30b375c422e)

**Comment by ericprud** [comment]
need feedback from @VladimirAlexiev on [spec changes](https://s3.amazonaws.com/pr-preview/shexSpec/spec/74d60b7...6b6331a.html#values) and [tests](https://github.com/shexSpec/shexTest/pull/23/commits/46c7f1a18711e063fbd199a98470a10af4d55658) before closing.

**Comment by VladimirAlexiev** [comment]
Spec sounds good, I like the ref to https://tools.ietf.org/html/rfc4647#section-3.3.1. Maybe say that `*` is not allowed, and what happens if I give an incomplete lang tag eg `@e` (answer: won't match any value).

Tests look correct, but:
- feel a bit uncomfortable about using unregistered sublang tags like `@fr-bel`
- Maybe do some case variation (the matching should be case-insensitive)

Cheers @ericprud !

**Comment by ericprud** [comment]
I was going to do a separate PR to add "*" to the [grammar](http://shex.io/shex-semantics-20170713/#prod-languageRange) a la
```
[55] languageRange ::= (LANGTAG | '*') ('~' languageExclusion*)?
```

I tried to find two region codes that where one was a substring of other. Do you know where I can find the canonical list of regions? I picked a valid three-letter ISO region code ("bel"). I guess I could switch from FR to DE and use the example from RFC4647 basic match.

Re: case variation, true. Early on, I had data files like `spo@fr.ttl` and `spo@FR.ttl` but I think some case-insensitive file system ate them long ago. Will re-add tests for that and for shex files matching `@FR`, `. - ~@FR` and `@FR~ - ~FR-BE`.

**Comment by VladimirAlexiev** [comment]
Regions: https://docs.google.com/spreadsheets/d/1M1yv9aBUmc-NyCJX69vOLUmH2uIglSwmDwgRgByI1AI/edit#gid=2001354273 and filter by type=region.
These are 2-letter country codes and 3-digit continent-like codes. So there are no "substring of another".

But if there were, the matching is still the same: next should come dash or end of string. I.e. `@en-G~` will not match `@en-GB` and `@en-GR`.

What do you want with `*`? Eg `@*-GB` to match any language spoken in Great Britain? 
- I think this falls under "extended matching" https://tools.ietf.org/html/rfc4647#section-3.3.2
- Check whether `langMatches()` supports it, I'm a bit doubftul

**Comment by ericprud** [comment]
Re case sensitivity, I varied the case in the [data](shexSpec/shexTest/pull/24) and the [schema](shexSpec/shexTest/pull/25). The latter raised [a round-tripping issue to RDF](#73). I invite you to review those PRs.

**Comment by ericprud** [comment]
It is our belief that the semantics in [ShEx 2.1 § 5.4.6 Values Constraint](http://shex.io/shex-semantics-20181122/#values) address this. Please close this issue if you agree.

**Comment by VladimirAlexiev** [comment]
I've read the section and I think it addresses this by reference to other standards. In particular I like:
st is a **basic language range** per Matching of Language Tags [rfc4647] section 2.1 and l matches st per the basic filtering scheme defined in [rfc4647] section 3.3.1.

In other words, one is not supposed to use an incomplete stem like `en-G~`
