### ISSUE TITLE
No way to say "any language-tagged string"

### ISSUE THREAD

**Issue by ericprud** [shexSpec/shex#74]
We don't have a way to specify any literal with a language tag. The closest we have is rather arcane by ruling out only unlikely language tags:
````
<S> { :p [. - @notalanguage] }
````
which would not match `<s>` in `<s> :p "asdf"@en .` but not any of  these graphs:
* `<s> :p <o> .`
* `<s> :p _:foo .`
* `<s> :p "asdf" .`
* `<s> :p "asdf"@notalanguage .`

**Correction**: one could also used a `rdf:langString`
```
<S> { :p rdf:langString }
```
Exclusions become awkward:
```
<S> { :p (rdf:langString AND NOT [@en @fr]) }
```

**Comment by ericprud** [comment]
(response moved from #78)

I had an [action item](https://github.com/shexSpec/shex/blob/master/meetings/20171121-minutes.md#pending-actions) to draft a proposal for an intuitive token for "any language-tagged string". I ended up using `@~` instead of `@*` ([see shex.js example](http://rawgit.com/shexSpec/shex.js/langString-ATstar/doc/shex-simple.html?schema=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0A%0A%3C%23LangString%3E%20rdf%3AlangString%0A%0A%3C%23LangStem%3E%20%5B%40en~%5D%0A%0A%3C%23Empty%3E%20%5B%40~%5D%0A%0A%3C%23EmptyExclEN%3E%20%5B%40~%20-%20%40en%5D%20%23%20rejects%20%22ab%22%40en%0A%0A%3C%23EmptyExclFR%3E%20%5B%40~%20-%20%40fr%5D%0A%0A%23%20%3C%23EmptyExclEmpty%3E%20%5B%40~%20-%20%40~%5D%20%3C--%20not%20valid%20in%20grammar%0A%0A%23%20%3C%23DotExclEmpty%3E%20%5B.%20-%20%40~%5D%20%3C--%20not%20valid%20in%20grammar%0A%0A%0A&data=&shape-map=%22ab%22%40en%40%3C%23LangString%3E%2C%0A%22ab%22%40en%40%3C%23LangStem%3E%2C%0A%22ab%22%40en%40%3C%23Empty%3E%2C%0A%22ab%22%40en%40%3C%23EmptyExclEN%3E%2C%0A%22ab%22%40en%40%3C%23EmptyExclFR%3E&interface=human&regexpEngine=threaded-val-nerr)). This worked in `shex.js` with [fewer than 10 changed lines](https://github.com/shexSpec/shex.js/commit/113c7ef28e57658f043a91839eb1ccf9dc8241d8).

```
<#LangString> rdf:langString

<#LangStem> [@en~]

<#Empty> [@~]

<#EmptyExclEN> [@~ - @en] # rejects "ab"@en

<#EmptyExclFR> [@~ - @fr]

# <#EmptyExclEmpty> [@~ - @~] <-- not valid in grammar

# <#DotExclEmpty> [. - @~] <-- not valid in grammar
```

**Comment by emulatingkat** [comment]
+1

**Comment by ericprud** [comment]
PRs:
+ [shexTest](https://github.com/shexSpec/shexTest/pull/36)
  + [3 schemas](https://github.com/shexSpec/shexTest/commit/f21acaba454cd337e9aae8cb01cd4dda15ca4108#diff-812a46ae982a29ebdee2f86dbe52dd46)
  + [11 validation tests](https://github.com/shexSpec/shexTest/commit/f21acaba454cd337e9aae8cb01cd4dda15ca4108#diff-e45ec9fb9aead8fb5d8f45ef1915cd9e)
  + [2 negative syntax tests](https://github.com/shexSpec/shexTest/pull/36/files#diff-762c54fa3305691819df3f85bb74e530)
+ [spec](https://github.com/shexSpec/spec/pull/26)
  + [1 extension to ShExC grammar](https://github.com/shexSpec/spec/compare/langString-ATstar?expand=1#diff-eacf331f0ffc35d4b482f1d15a887d3b)
+ [grammar](https://github.com/shexSpec/grammar/pull/7)


TODO: someone should look at [5.4.6 Values Constraint](https://shexspec.github.io/spec/#values) and decide whether there needs to be more explanatory text for an empty stem.
