### ISSUE TITLE
`nodeIn` appears incorrect for blank nodes

### ISSUE THREAD

**Issue by hsolbrig** [shexSpec/shex#79]
http://shex.io/shex-semantics/#values currently asserts that blank node can match *any* stem.  As an example, if s is a LanguageStem and n is a blank node, the specification states that nodIn is satisfied if fn:startswith(identifier(n), LanguageStem.stem).

There doesn't actually seem to be enough in the grammar to allow stem matching with blank nodes.

**Comment by ericprud** [comment]
Agreed. [[49] valueSetValue](http://shex.io/shex-semantics/#prod-valueSetValue) defines {iri,literal,language}Range, eliding anything like `bnodeRange`. There are no related tests in the test suite and I don't know of any implementations that support bnode valueSetValues.

PROPOSE: remove this text from [nodeIn](http://shex.io/shex-semantics/#nodeIn):

> n is a blank node with identifier l and fn:starts-with(l, st).

**Comment by jimkont** [comment]
RESOLVED with votes from @emulatingkat, @gkellogg, @hsolbrig, @jimkont, @tombaker, @lucaswerkmeister, and @andrawaag that reacted with thumbs up on https://github.com/shexSpec/shex/issues/79#issuecomment-357547513.

Action to change the spec before we close the issue
