### ISSUE TITLE
Single value sets

### ISSUE THREAD

**Issue by labra** [shexSpec/shex#8]
A very common pattern is to define a value set with a single element. For example:

``` turtle
:SpanishProduct {
 :country [:Spain]
}
```

Although this syntax is ok, one of the most common errors is to try to define the previous shape as:

``` turtle
:SpanishProduct {
 :country :Spain
}
```

which is not what is intended (that declares that values should belong to a type `:Spain`.

Having some syntactic sugar for single value shapes would make this feature less error-prone. One possibility would be the equals sign.

``` turtle
:SpanishProduct {
 :country = :Spain
}
```

**Comment by ericprud** [comment]
my temptation is to save "=" for defaults, which don't have any
current semantics but could be useful for form-building etc.
-- 
-ericP

office: +1.617.599.3509
mobile: +33.6.80.80.35.59

(eric@w3.org)
Feel free to forward this message to any list for any purpose other than
email address distribution.

There are subtle nuances encoded in font variation and clever layout
which can only be seen by printing this message on high-clay paper.

**Comment by andrawaag** [comment]
We close this due to inactivity, @labra feel free to reopen if still relevant.
