### ISSUE TITLE
Datatype example uses non-sparql11 datatype

### ISSUE THREAD

**Issue by hsolbrig** [shexSpec/shex#81]
Example 1 in 5.4.3 Datatype Constraints has a pass and a fail for `xsd:date`.  The spec asserts "Only datatypes supported by SPARQL MUST be tested but ShEx extensions MAY add support for other datatypes. " and, as `xsd:date` is not supported by SPARQL, the results of the test are unspecified.

**Comment by ericprud** [comment]
I believe new wording is required here. The behavior required by the test suite is actually to support datatypes not listed in SPARQL, but not to require any type inference about them. This is consistent with SPARQL which has tests for e.g. `"ii"^^my:romanNumeral`.

**Comment by ericprud** [comment]
We need to enumerate for which datatypes ShEx requires validation of the lexical form.

**Comment by ericprud** [comment]
PROPOSED: ShEx validates lexical forms of:
1. the subset of XSD primitive types supported by SPARQL1.1 plus `xsd:date` and `xsd:time`.
2. the subset of XSD derived numeric types supported by SPARQL1.1.

**Comment by jimkont** [comment]
Resolved with votes from @ericprud, @labra, @gkellogg, @hsolbrig, @emulatingkat, @larsgsvensson, @jimkont, @tombaker, and @lucaswerkmeister that reacted with thumbs up on https://github.com/shexSpec/shex/issues/81#issuecomment-368446352

Action before we close: Update the spec accordingly

**Comment by ericprud** [comment]
added this to [§ 5.4.3 Datatype Constraints](https://shexspec.github.io/spec/#datatype):

>  The lexical form and numeric value (where applicable) of all datatypes required by <a data-cite="sparql11-query#FunctionMapping">SPARQL XPath Constructor Functions</a> MUST be tested for conformance with the corresponding XML Schema form.
>  ShEx extensions MAY add support for other datatypes.
